server:
  port: 7002
    
spring:
   application:
      name: consumer
      
eureka:
   instance:
      instance-id: consumer:7002
      prefer-ip-address: true
   client:
      serviceUrl:
         # defaultZone: http://localhost:5001/eureka/
         defaultZone: http://eureka5001.com:5001/eureka/,http://eureka5002.com:5002/eureka/,http://eureka5003.com:5003/eureka/
      register-with-eureka: true
      fetch-registry: true

feign: 
   hystrix: 
      enabled: true 

info:
   app.name: wzcloud
   company.name: www.wzcloud.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
   