server:
  port: 5003

eureka:
  instance:
    hostname: eureka5003.com
  client:
    serviceUrl:
      defaultZone: http://eureka5002.com:5002/eureka/,http://eureka5001.com:5001/eureka/
    register-with-eureka: false
    fetch-registry: false

info:
   app.name: wzcloud
   company.name: www.wzcloud.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$








